#!/usr/bin/env python3
"""Clean Mia (or any person) gallery: drop AI/fan-art, weak identity, dupes.

Reads target/<person>.zip, scores each crop with InsightFace vs a studio
centroid, URL/source heuristics, and optional blur (too-smooth = synthetic).
Writes cleaned zip + quarantine folder.

Usage:
  python scripts/clean_target_gallery.py --person mia --rebuild-zip
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import shutil
import zipfile
from pathlib import Path

import cv2
import imagehash
import numpy as np
from insightface.app import FaceAnalysis
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PHASH_MAX_DIST = 6
MIN_DET = 0.30
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

# URL / path hints for non-photographic or synthetic images
JUNK_RE = re.compile(
    r"(stablediffusion|stable-diffusion|midjourney|dall[\-\s]?e|wixmp|"
    r"artstation\.com|fineartamerica|shutterstock.*illustration|"
    r"digital[\-_ ]?(portrait|drawing|art)|/drawing|wallpaper[s]?\.com|"
    r"imgcdn\.stablediffusion|vulplex\.com|panthalassanews|"
    r"ijyoyo\.com|dancewearfashion|stock-photo.*illustration|"
    r"\.png/v1/fill|ai-generated|generated by ai)",
    re.I,
)

# Prefer real press / social sources when deduping ambiguous pairs
GOOD_SOURCE_RE = re.compile(
    r"(wikimedia|getty|newsweek|vogue|imdb|instagram|reddit|flickr|"
    r"purepeople|hawtcelebs|masala|freepressjournal|cloudfront|"
    r"assets\.newsweek|miakalifa\.live|youtube|tiktok)",
    re.I,
)


def unit(v):
    n = float(np.linalg.norm(v))
    return v / n if n > 0 else v


def load_bgr(raw: bytes):
    arr = np.frombuffer(raw, dtype=np.uint8)
    img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if img is not None:
        return img
    try:
        pil = Image.open(io.BytesIO(raw)).convert("RGB")
        return cv2.cvtColor(np.array(pil), cv2.COLOR_RGB2BGR)
    except Exception:
        return None


def phash_bgr(bgr):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    return imagehash.phash(Image.fromarray(rgb))


def laplacian_var(bgr) -> float:
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    return float(cv2.Laplacian(gray, cv2.CV_64F).var())


def url_for_crop(crop_name: str, manifest: dict) -> str:
    for e in manifest.get("entries", []):
        if e.get("crop") == crop_name:
            return str(e.get("url", ""))
    return ""


def arc_to_crop_name(arc: str) -> str:
    return Path(arc).name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--person", default="mia")
    ap.add_argument("--zip", type=Path, default=None)
    ap.add_argument("--sim-min", type=float, default=0.42,
                    help="Drop crops below this InsightFace cosine to centroid.")
    ap.add_argument("--lap-min", type=float, default=35.0,
                    help="Drop very smooth images (likely AI/airbrushed).")
    ap.add_argument("--rebuild-zip", action="store_true")
    args = ap.parse_args()

    person = args.person
    zip_path = args.zip or ROOT / "target" / f"{person}.zip"
    manifest_path = ROOT / "target" / "harvest" / person / "manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {"entries": []}
    url_by_crop = {e["crop"]: e.get("url", "") for e in manifest["entries"] if e.get("crop")}

    quarantine = ROOT / "target" / "harvest" / person / "quarantine"
    if quarantine.exists():
        shutil.rmtree(quarantine)
    quarantine.mkdir(parents=True, exist_ok=True)

    os.environ.setdefault("OMP_NUM_THREADS", "4")
    app = FaceAnalysis(name="buffalo_l", providers=["CPUExecutionProvider"])
    app.prepare(ctx_id=-1, det_size=(640, 640))

    items = []  # (arc, raw, bgr)
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if Path(name).suffix.lower() not in IMAGE_EXTS:
                continue
            if name.startswith("__MACOSX/") or Path(name).name.startswith("._"):
                continue
            raw = zf.read(name)
            bgr = load_bgr(raw)
            if bgr is not None:
                items.append((name, raw, bgr))

    # Centroid from top-detection faces not flagged as junk URL
    embs = []
    for arc, raw, bgr in items:
        crop = arc_to_crop_name(arc)
        url = url_by_crop.get(crop, arc)
        if JUNK_RE.search(url):
            continue
        faces = app.get(bgr)
        if not faces:
            continue
        f = max(faces, key=lambda x: float(x.det_score))
        if float(f.det_score) < MIN_DET:
            continue
        embs.append(unit(np.asarray(f.normed_embedding, dtype=np.float64)))
    if len(embs) < 10:
        raise SystemExit(f"too few reference faces for centroid ({len(embs)})")
    centroid = unit(np.mean(embs, axis=0))
    print(f"centroid from {len(embs)} reference faces")

    kept, dropped = [], []
    phashes: list[imagehash.ImageHash] = []

    for arc, raw, bgr in items:
        crop = arc_to_crop_name(arc)
        url = url_by_crop.get(crop, arc)
        reason = None

        if JUNK_RE.search(url) or JUNK_RE.search(arc):
            reason = "junk_url"

        lv = laplacian_var(bgr)
        if reason is None and lv < args.lap_min:
            reason = f"too_smooth(lap={lv:.1f})"

        faces = app.get(bgr)
        if reason is None:
            if not faces:
                reason = "no_face"
            else:
                f = max(faces, key=lambda x: float(x.det_score))
                if float(f.det_score) < MIN_DET:
                    reason = "low_det"
                else:
                    sim = float(np.dot(unit(np.asarray(f.normed_embedding, dtype=np.float64)), centroid))
                    if sim < args.sim_min:
                        reason = f"low_sim({sim:.2f})"

        if reason is None:
            h = phash_bgr(bgr)
            if any(h - old <= PHASH_MAX_DIST for old in phashes):
                reason = "dup_phash"
            else:
                phashes.append(h)
                kept.append((arc, raw, url, lv))

        if reason is not None:
            dropped.append((arc, raw, reason, url))

    # Sort kept: prefer good sources when reviewing stats
    print(f"\n{person}.zip  in={len(items)}  kept={len(kept)}  dropped={len(dropped)}")
    from collections import Counter
    print("drop reasons:", dict(Counter(r for _, _, r, _ in dropped)))

    for arc, raw, reason, url in dropped:
        out = quarantine / f"{Path(arc).stem}__{reason.replace('/', '-')[:40]}.jpg"
        out.write_bytes(raw)

    if args.rebuild_zip:
        cfg_path = ROOT / "scripts" / "harvest_queries.json"
        prefix = json.loads(cfg_path.read_text())[person]["zip_prefix"]
        tmp = zip_path.with_suffix(".zip.tmp")
        with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for arc, raw, url, lv in sorted(kept, key=lambda x: x[0]):
                # preserve in_the_wild paths; new scout -> mia/
                new_arc = arc if "/" in arc else f"{prefix}/{Path(arc).name}"
                zf.writestr(new_arc, raw)
        bak = zip_path.with_suffix(".zip.bak_pre_clean")
        if not bak.exists():
            shutil.copy2(zip_path, bak)
        tmp.replace(zip_path)
        print(f"rebuilt {zip_path}  ({len(kept)} images)  backup -> {bak.name}")

    report = ROOT / "target" / "harvest" / person / "clean_report.json"
    report.write_text(json.dumps({
        "in": len(items), "kept": len(kept), "dropped": len(dropped),
        "drop_reasons": dict(Counter(r for _, _, r, _ in dropped)),
    }, indent=2))
    print(f"quarantine -> {quarantine}")
    print(f"report -> {report}")


if __name__ == "__main__":
    main()
